### ISSUE TITLE
Introduction: Esto me parece peligroso 

### ISSUE THREAD

**Issue by dbustosp** [gvillarroel/synthetic-data-for-text#10]
https://github.com/gvillarroel/synthetic-data-for-text/blob/cf5db2dbdb8bc4d4a1af07f07a1e270998bc082b/docs/tesis/caps/introduccion.tex#L38

Es necesario ponerlo? Se divulga parte de la IP de K&L?

**Comment by gvillarroel** [comment]
borrado
