### ISSUE TITLE
Introduction: Esto tambien me parece peligroso

### ISSUE THREAD

**Issue by dbustosp** [gvillarroel/synthetic-data-for-text#11]
https://github.com/gvillarroel/synthetic-data-for-text/blob/cf5db2dbdb8bc4d4a1af07f07a1e270998bc082b/docs/tesis/caps/introduccion.tex#L40C1-L41C1

Muy peligroso

**Comment by gvillarroel** [comment]
Borrado  PDZ, solo se indica que es protegida
