### ISSUE TITLE
Pregunta General: Equifax o no Equifax? 

### ISSUE THREAD

**Issue by dbustosp** [gvillarroel/synthetic-data-for-text#12]
https://github.com/gvillarroel/synthetic-data-for-text/blob/cf5db2dbdb8bc4d4a1af07f07a1e270998bc082b/docs/tesis/caps/introduccion.tex#L32-L34

Cual es el objetivo de la tesis, relacionarlo con EFX o no EFX? Porque si es asi entonces tienes que decirlo en el Abstract, para setear el scope de entrada.

**Comment by gvillarroel** [comment]
no es con EFX, es la generación de data sintetica, EFX es solo un ejemplo de uso.
