### ISSUE TITLE
Introduction: No digas explicitamente el libro 

### ISSUE THREAD

**Issue by dbustosp** [gvillarroel/synthetic-data-for-text#9]
https://github.com/gvillarroel/synthetic-data-for-text/blob/cf5db2dbdb8bc4d4a1af07f07a1e270998bc082b/docs/tesis/caps/introduccion.tex#L6-L10

Puedes decir algo como: 

```
Los datos sintéticos ofrecen dos beneficios principales [8]: 
1. ...
2. ...
```

**Comment by gvillarroel** [comment]
cambiado
